name: Build API in Docker Container and Deploy Container to Registry 

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/api/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'src/api/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  Build_Container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Login
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
    
      - name: Build and push Docker image
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/telemetry:v0.8,${{ secrets.DOCKER_HUB_USERNAME }}/telemetry:latest

